{
 "title": "AXPERT",
 "description": "Dashboard for remote monitoring AXPERT Inverters",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "BAT Voltage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "alias": "Battery voltage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "pip_query_general_status",
     "rawSql": "SELECT \nunix_timestamp(created) AS \"time\",\n  (var9) voltage\nFROM QPIGS\nWHERE\n  $__timeFilter(created)\nORDER BY created"
    }
   ]
  },
  {
   "title": "BAT Charging / Discharging",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "Charging",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "pip_query_general_status",
     "rawSql": "SELECT \nunix_timestamp(created) AS \"time\",\n  (var10*var9) charging\nFROM QPIGS\nWHERE\n  $__timeFilter(created)\nORDER BY created"
    },
    {
     "alias": "Discharging",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "pip_query_general_status",
     "rawSql": "SELECT\n  unix_timestamp(created) AS \"time\",\n  (var16*var9*(-1)) discharging\nFROM QPIGS\nWHERE\n  $__timeFilter(created)\nORDER BY created"
    }
   ]
  },
  {
   "title": "BAT Voltage",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "voltage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pip_query_general_status",
     "rawSql": "SELECT\n  created AS \"time\",\n  var9\nFROM QPIGS\nWHERE\n  $__timeFilter(created)\nORDER BY created"
    }
   ]
  },
  {
   "title": "Total Load",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pip_query_general_status",
     "rawSql": "SELECT\n  created AS \"time\",\n  var6 + 60\nFROM QPIGS\nWHERE\n  $__timeFilter(created)\nORDER BY created"
    }
   ]
  },
  {
   "title": "BAT SoC",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pip_query_general_status",
     "rawSql": "SELECT\n  created AS \"time\",\n  var4\nFROM BMS\nWHERE\n  $__timeFilter(created)\nORDER BY created"
    }
   ]
  },
  {
   "title": "BAT Charging Power",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "amperage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pip_query_general_status",
     "rawSql": "SELECT\n  created AS \"time\",\n  (var9*var10)\nFROM QPIGS\nWHERE\n  $__timeFilter(created)\nORDER BY created"
    }
   ]
  },
  {
   "title": "PV Power",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pip_query_general_status",
     "rawSql": "SELECT\n  created AS \"time\",\n  (var13*var14) pv_power\nFROM QPIGS\nWHERE\n  $__timeFilter(created)\nORDER BY created"
    }
   ]
  },
  {
   "title": "BAT Discharging Power",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pip_query_general_status",
     "rawSql": "SELECT\n  created AS \"time\",\n  (var9*var16)\nFROM QPIGS\nWHERE\n  $__timeFilter(created)\nORDER BY created"
    }
   ]
  },
  {
   "title": "Output Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "Active Power AC",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pip_query_general_status",
     "rawSql": "SELECT \nunix_timestamp(created) AS \"time\",\n  (var6) \"true\"\nFROM QPIGS\nWHERE\n  $__timeFilter(created)\nORDER BY created"
    }
   ]
  },
  {
   "title": "PV Power",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "Reactive Power AC",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pip_query_general_status",
     "rawSql": "SELECT \nunix_timestamp(created) AS \"time\",\n  (var13*var14) power\nFROM QPIGS\nWHERE\n  $__timeFilter(created)\nORDER BY created"
    }
   ]
  },
  {
   "title": "BAT Charging Current",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pip_query_general_status",
     "rawSql": "SELECT\n  created AS \"time\",\n  var10\nFROM QPIGS\nWHERE\n  $__timeFilter(created)\nORDER BY created"
    }
   ]
  },
  {
   "title": "BAT Discharging Current",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pip_query_general_status",
     "rawSql": "SELECT\n  created AS \"time\",\n  var16\nFROM QPIGS\nWHERE\n  $__timeFilter(created)\nORDER BY created"
    }
   ]
  },
  {
   "title": "Floating Voltage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pip_query_device_rated_information",
     "rawSql": "SELECT\n  created AS \"time\",\n  var12\nFROM QPIRI\nWHERE\n  $__timeFilter(created)\nORDER BY created"
    }
   ]
  },
  {
   "title": "Bulk Voltage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pip_query_device_rated_information",
     "rawSql": "SELECT\n  created AS \"time\",\n  var11\nFROM QPIRI\nWHERE\n  $__timeFilter(created)\nORDER BY created"
    }
   ]
  },
  {
   "title": "Re-charge Voltage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pip_query_device_rated_information",
     "rawSql": "SELECT\n  created AS \"time\",\n  var9\nFROM QPIRI\nWHERE\n  $__timeFilter(created)\nORDER BY created"
    }
   ]
  },
  {
   "title": "Re-discharge Voltage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pip_query_device_rated_information",
     "rawSql": "SELECT\n  created AS \"time\",\n  var23\nFROM QPIRI\nWHERE\n  $__timeFilter(created)\nORDER BY created"
    }
   ]
  },
  {
   "title": "Output Voltage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pip_query_general_status",
     "rawSql": "SELECT\n  created AS \"time\",\n  var3\nFROM QPIGS\nWHERE\n  $__timeFilter(created)\nORDER BY created"
    }
   ]
  },
  {
   "title": "Output Frequency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pip_query_general_status",
     "rawSql": "SELECT\n  created AS \"time\",\n  var4\nFROM QPIGS\nWHERE\n  $__timeFilter(created)\nORDER BY created"
    }
   ]
  },
  {
   "title": "Grid Voltage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pip_query_general_status",
     "rawSql": "SELECT\n  created AS \"time\",\n  var1\nFROM QPIGS\nWHERE\n  $__timeFilter(created)\nORDER BY created"
    }
   ]
  },
  {
   "title": "Grid Frequency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pip_query_general_status",
     "rawSql": "SELECT\n  created AS \"time\",\n  var2\nFROM QPIGS\nWHERE\n  $__timeFilter(created)\nORDER BY created"
    }
   ]
  },
  {
   "title": "PV Voltage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pip_query_general_status",
     "rawSql": "SELECT\n  created AS \"time\",\n  var14\nFROM QPIGS\nWHERE\n  $__timeFilter(created)\nORDER BY created"
    }
   ]
  },
  {
   "title": "PV Current",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pip_query_general_status",
     "rawSql": "SELECT\n  created AS \"time\",\n  var13\nFROM QPIGS\nWHERE\n  $__timeFilter(created)\nORDER BY created"
    }
   ]
  },
  {
   "title": "Max Charging Current",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pip_query_device_rated_information",
     "rawSql": "SELECT\n  created AS \"time\",\n  var15\nFROM QPIRI\nWHERE\n  $__timeFilter(created)\nORDER BY created"
    }
   ]
  },
  {
   "title": "Grid Max Charging Current",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pip_query_device_rated_information",
     "rawSql": "SELECT\n  created AS \"time\",\n  var14\nFROM QPIRI\nWHERE\n  $__timeFilter(created)\nORDER BY created"
    }
   ]
  },
  {
   "title": "Device mode",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  created AS \"time\",\n  var1\nFROM QMOD\nWHERE\n  $__timeFilter(created)\nORDER BY created"
    }
   ]
  },
  {
   "title": "Charger Source Priority",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pip_query_general_status",
     "rawSql": "SELECT\n  created AS \"time\",\n  var18\nFROM QPIRI\nWHERE\n  $__timeFilter(created)\nORDER BY created"
    }
   ]
  },
  {
   "title": "Output source priority",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pip_query_general_status",
     "rawSql": "SELECT\n  created AS \"time\",\n  var17\nFROM QPIRI\nWHERE\n  $__timeFilter(created)\nORDER BY created"
    }
   ]
  },
  {
   "title": "Output load %",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pip_query_general_status",
     "rawSql": "SELECT\n  created AS \"time\",\n  var7\nFROM QPIGS\nWHERE\n  $__timeFilter(created)\nORDER BY created"
    }
   ]
  },
  {
   "title": "Source",
   "type": "cloudspout-button-panel",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 41 },
   "targets": [
    {
     "rawSql": "SELECT\n  created AS \"time\",\n  var1\nFROM Q1\nWHERE\n  $__timeFilter(created)\nORDER BY created"
    }
   ]
  },
  {
   "title": "Source",
   "type": "cloudspout-button-panel",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 41 },
   "targets": [
    {
     "rawSql": "SELECT\n  created AS \"time\",\n  var1\nFROM Q1\nWHERE\n  $__timeFilter(created)\nORDER BY created"
    }
   ]
  },
  {
   "title": "Source",
   "type": "cloudspout-button-panel",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 41 },
   "targets": [
    {
     "rawSql": "SELECT\n  created AS \"time\",\n  var1\nFROM Q1\nWHERE\n  $__timeFilter(created)\nORDER BY created"
    }
   ]
  },
  {
   "title": "Charger",
   "type": "cloudspout-button-panel",
   "gridPos": { "h": 3, "w": 4, "x": 9, "y": 41 },
   "targets": [
    {
     "rawSql": "SELECT\n  created AS \"time\",\n  var1\nFROM Q1\nWHERE\n  $__timeFilter(created)\nORDER BY created"
    }
   ]
  },
  {
   "title": "Charger",
   "type": "cloudspout-button-panel",
   "gridPos": { "h": 3, "w": 4, "x": 13, "y": 41 },
   "targets": [
    {
     "rawSql": "SELECT\n  created AS \"time\",\n  var1\nFROM Q1\nWHERE\n  $__timeFilter(created)\nORDER BY created"
    }
   ]
  },
  {
   "title": "Charger",
   "type": "cloudspout-button-panel",
   "gridPos": { "h": 3, "w": 4, "x": 17, "y": 41 },
   "targets": [
    {
     "rawSql": "SELECT\n  created AS \"time\",\n  var1\nFROM Q1\nWHERE\n  $__timeFilter(created)\nORDER BY created"
    }
   ]
  },
  {
   "title": "Charger",
   "type": "cloudspout-button-panel",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 41 },
   "targets": [
    {
     "rawSql": "SELECT\n  created AS \"time\",\n  var1\nFROM Q1\nWHERE\n  $__timeFilter(created)\nORDER BY created"
    }
   ]
  },
  {
   "title": "Grid",
   "type": "cloudspout-button-panel",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 44 },
   "targets": [
    {
     "rawSql": "SELECT\n  created AS \"time\",\n  var1\nFROM Q1\nWHERE\n  $__timeFilter(created)\nORDER BY created"
    }
   ]
  },
  {
   "title": "Grid",
   "type": "cloudspout-button-panel",
   "gridPos": { "h": 3, "w": 7, "x": 6, "y": 44 },
   "targets": [
    {
     "rawSql": "SELECT\n  created AS \"time\",\n  var1\nFROM Q1\nWHERE\n  $__timeFilter(created)\nORDER BY created"
    }
   ]
  },
  {
   "title": "Controller",
   "type": "cloudspout-button-panel",
   "gridPos": { "h": 3, "w": 5, "x": 13, "y": 44 },
   "targets": [
    {
     "rawSql": "SELECT\n  created AS \"time\",\n  var1\nFROM Q1\nWHERE\n  $__timeFilter(created)\nORDER BY created"
    }
   ]
  },
  {
   "title": "Controller",
   "type": "cloudspout-button-panel",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 44 },
   "targets": [
    {
     "rawSql": "SELECT\n  created AS \"time\",\n  var1\nFROM Q1\nWHERE\n  $__timeFilter(created)\nORDER BY created"
    }
   ]
  },
  {
   "title": "PV Voltage / Current",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "alias": "Panels Voltage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pip_query_general_status",
     "rawSql": "SELECT \nunix_timestamp(created) AS \"time\",\n  (var14) voltage, (var13) current\nFROM QPIGS\nWHERE\n  $__timeFilter(created)\nORDER BY created"
    }
   ]
  },
  {
   "title": "Inverter Temperature",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "Inverter Temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pip_query_general_status",
     "rawSql": "SELECT \nunix_timestamp(created) AS \"time\",\n  (var12) temperature\nFROM QPIGS\nWHERE\n  $__timeFilter(created)\nORDER BY created"
    }
   ]
  },
  {
   "title": "Output Voltage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \nunix_timestamp(created) AS \"time\",\n  (var3) voltage\nFROM QPIGS\nWHERE\n  $__timeFilter(created)\nORDER BY created"
    }
   ]
  },
  {
   "title": "Output Frequency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "rothz" }
   ],
   "targets": [
    {
     "alias": "Output AC Frequency (Hz)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pip_query_general_status",
     "rawSql": "SELECT \nunix_timestamp(created) AS \"time\",\n  (var4) frequency\nFROM QPIGS\nWHERE\n  $__timeFilter(created)\nORDER BY created"
    }
   ]
  }
 ]
}