{
 "title": "BMS",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "BAT SoC",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "Battery voltage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "pip_query_general_status",
     "rawSql": "SELECT\n  unix_timestamp(created) AS \"time\",\n  (var4) soc\nFROM BMS\nWHERE\n  $__timeFilter(created)\nORDER BY created"
    }
   ]
  },
  {
   "title": "BAT Current",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    {
     "alias": "Battery voltage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "pip_query_general_status",
     "rawSql": "SELECT\n  unix_timestamp(created) AS \"time\",\n  if(var3>0,var3,0) as charging\nFROM BMS\nWHERE\n  $__timeFilter(created)\nORDER BY created"
    },
    {
     "rawSql": "SELECT\n  unix_timestamp(created) AS \"time\",\n  if(var3<0,var3,0) as discharging\nFROM BMS\nWHERE\n  $__timeFilter(created)\nORDER BY created"
    }
   ]
  },
  {
   "title": "BAT Voltage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "alias": "Battery voltage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "pip_query_general_status",
     "rawSql": "SELECT\n  unix_timestamp(created) AS \"time\",\n  (var1) voltage\nFROM BMS\nWHERE\n  $__timeFilter(created)\nORDER BY created"
    }
   ]
  },
  {
   "title": "BAT Temperature",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "Battery voltage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "pip_query_general_status",
     "rawSql": "SELECT\n  unix_timestamp(created) AS \"time\",\n  (var40) temp\nFROM BMS\nWHERE\n  $__timeFilter(created)\nORDER BY created"
    }
   ]
  },
  {
   "title": "Balancer #1",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Battery voltage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "pip_query_general_status",
     "rawSql": "SELECT \nunix_timestamp(created) AS \"time\",\n  abs(var25-var24)*1000 set1, abs(var26-var25)*1000 set2, abs(var27-var26)*1000 set3, abs(var28-var27)*1000 set4, abs(var29-var28)*1000 set5, abs(var30-var29)*1000 set6, abs(var31-var30)*1000 set7\nFROM BMS\nWHERE\n  $__timeFilter(created)\nORDER BY created\n"
    }
   ]
  },
  {
   "title": "Balancer #2",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Battery voltage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "pip_query_general_status",
     "rawSql": "SELECT \nunix_timestamp(created) AS \"time\",\n  abs(var33-var32)*1000 set1, abs(var34-var33)*1000 set2, abs(var35-var34)*1000 set3, abs(var36-var35)*1000 set4, abs(var37-var36)*1000 set5, abs(var38-var37)*1000 set6, abs(var39-var38)*1000 set7\nFROM BMS\nWHERE\n  $__timeFilter(created)\nORDER BY created\n"
    }
   ]
  },
  {
   "title": "Cell #1",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "alias": "Battery voltage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "pip_query_general_status",
     "rawSql": "SELECT\n  unix_timestamp(created) AS \"time\",\n  (var24) voltage\nFROM BMS\nWHERE\n  $__timeFilter(created)\nORDER BY created"
    }
   ]
  },
  {
   "title": "Cell #2",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 21 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "alias": "Battery voltage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "pip_query_general_status",
     "rawSql": "SELECT\n  unix_timestamp(created) AS \"time\",\n  (var25) voltage\nFROM BMS\nWHERE\n  $__timeFilter(created)\nORDER BY created"
    }
   ]
  },
  {
   "title": "Cell #3",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "alias": "Battery voltage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "pip_query_general_status",
     "rawSql": "SELECT\n  unix_timestamp(created) AS \"time\",\n  (var26) voltage\nFROM BMS\nWHERE\n  $__timeFilter(created)\nORDER BY created"
    }
   ]
  },
  {
   "title": "Cell #4",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 21 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "alias": "Battery voltage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "pip_query_general_status",
     "rawSql": "SELECT\n  unix_timestamp(created) AS \"time\",\n  (var27) voltage\nFROM BMS\nWHERE\n  $__timeFilter(created)\nORDER BY created"
    }
   ]
  },
  {
   "title": "Cell #5",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "alias": "Battery voltage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "pip_query_general_status",
     "rawSql": "SELECT\n  unix_timestamp(created) AS \"time\",\n  (var28) voltage\nFROM BMS\nWHERE\n  $__timeFilter(created)\nORDER BY created"
    }
   ]
  },
  {
   "title": "Cell #6",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 27 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "alias": "Battery voltage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "pip_query_general_status",
     "rawSql": "SELECT\n  unix_timestamp(created) AS \"time\",\n  (var29) voltage\nFROM BMS\nWHERE\n  $__timeFilter(created)\nORDER BY created"
    }
   ]
  },
  {
   "title": "Cell #7",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "alias": "Battery voltage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "pip_query_general_status",
     "rawSql": "SELECT\n  unix_timestamp(created) AS \"time\",\n  (var30) voltage\nFROM BMS\nWHERE\n  $__timeFilter(created)\nORDER BY created"
    }
   ]
  },
  {
   "title": "Cell #8",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 27 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "alias": "Battery voltage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "pip_query_general_status",
     "rawSql": "SELECT\n  unix_timestamp(created) AS \"time\",\n  (var31) voltage\nFROM BMS\nWHERE\n  $__timeFilter(created)\nORDER BY created"
    }
   ]
  },
  {
   "title": "Cell #9",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "alias": "Battery voltage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "pip_query_general_status",
     "rawSql": "SELECT\n  unix_timestamp(created) AS \"time\",\n  (var32) voltage\nFROM BMS\nWHERE\n  $__timeFilter(created)\nORDER BY created"
    }
   ]
  },
  {
   "title": "Cell #10",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 33 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "alias": "Battery voltage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "pip_query_general_status",
     "rawSql": "SELECT\n  unix_timestamp(created) AS \"time\",\n  (var33) voltage\nFROM BMS\nWHERE\n  $__timeFilter(created)\nORDER BY created"
    }
   ]
  },
  {
   "title": "Cell #11",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "alias": "Battery voltage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "pip_query_general_status",
     "rawSql": "SELECT\n  unix_timestamp(created) AS \"time\",\n  (var34) voltage\nFROM BMS\nWHERE\n  $__timeFilter(created)\nORDER BY created"
    }
   ]
  },
  {
   "title": "Cell #12",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 33 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "alias": "Battery voltage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "pip_query_general_status",
     "rawSql": "SELECT\n  unix_timestamp(created) AS \"time\",\n  (var35) voltage\nFROM BMS\nWHERE\n  $__timeFilter(created)\nORDER BY created"
    }
   ]
  },
  {
   "title": "Cell #13",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "alias": "Battery voltage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "pip_query_general_status",
     "rawSql": "SELECT\n  unix_timestamp(created) AS \"time\",\n  (var36) voltage\nFROM BMS\nWHERE\n  $__timeFilter(created)\nORDER BY created"
    }
   ]
  },
  {
   "title": "Cell #14",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 39 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "alias": "Battery voltage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "pip_query_general_status",
     "rawSql": "SELECT\n  unix_timestamp(created) AS \"time\",\n  (var37) voltage\nFROM BMS\nWHERE\n  $__timeFilter(created)\nORDER BY created"
    }
   ]
  },
  {
   "title": "Cell #15",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "alias": "Battery voltage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "pip_query_general_status",
     "rawSql": "SELECT\n  unix_timestamp(created) AS \"time\",\n  (var38) voltage\nFROM BMS\nWHERE\n  $__timeFilter(created)\nORDER BY created"
    }
   ]
  },
  {
   "title": "Cell #16",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 39 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "alias": "Battery voltage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "pip_query_general_status",
     "rawSql": "SELECT\n  unix_timestamp(created) AS \"time\",\n  (var39) voltage\nFROM BMS\nWHERE\n  $__timeFilter(created)\nORDER BY created"
    }
   ]
  },
  {
   "title": "BAT Cycles",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pip_query_general_status",
     "rawSql": "SELECT\n  unix_timestamp(created) AS \"time\",\n  var23\nFROM BMS\nWHERE\n  $__timeFilter(created)\nORDER BY created"
    }
   ]
  },
  {
   "title": "Max (V) Cell #",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pip_query_general_status",
     "rawSql": "SELECT\n  unix_timestamp(created) AS \"time\",\n  var6\nFROM BMS\nWHERE\n  $__timeFilter(created)\nORDER BY created"
    }
   ]
  },
  {
   "title": "Min (V) Cell #",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pip_query_general_status",
     "rawSql": "SELECT\n  unix_timestamp(created) AS \"time\",\n  var8\nFROM BMS\nWHERE\n  $__timeFilter(created)\nORDER BY created"
    }
   ]
  },
  {
   "title": "BMS Charging",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pip_query_general_status",
     "rawSql": "SELECT\n  unix_timestamp(created) AS \"time\",\n  var14\nFROM BMS\nWHERE\n  $__timeFilter(created)\nORDER BY created"
    }
   ]
  },
  {
   "title": "BMS Discharging",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pip_query_general_status",
     "rawSql": "SELECT\n  unix_timestamp(created) AS \"time\",\n  var15\nFROM BMS\nWHERE\n  $__timeFilter(created)\nORDER BY created"
    }
   ]
  }
 ]
}