{
 "title": "STATS",
 "description": "AXPERT Statistics",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30m",
 "panels": [
  {
   "title": "PV Power",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "Inverter Power",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "W",
     "query": "SELECT mean(\"value\") FROM \"W\" WHERE (\"entity_id\" = 'metert_power_a') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "rawSql": "SELECT\nunix_timestamp(created) AS \"time\",\n  (var13*var14) power\nFROM QPIGS\nWHERE\n  $__timeFilter(created)\nORDER BY created",
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "inverter_power" }
     ]
    }
   ]
  },
  {
   "title": "Today",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Exported Energy",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kWh",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(CONVERT_TZ(h,'+00:00','+2:00')) DIV 86400 * 86400 AS \"time\",\n  sum(var2) AS \"production\"\nFROM VIEW2\nWHERE\n  $__timeFilter(h)\nGROUP BY  UNIX_TIMESTAMP(CONVERT_TZ(h,'+00:00','+2:00')) DIV 86400 * 86400",
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "exported_energy_daily" }
     ]
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(CONVERT_TZ(h,'+00:00','+2:00')) DIV 86400 * 86400 AS \"time\",\n  sum(var1) AS \"consumption\"\nFROM VIEW2\nWHERE\n  $__timeFilter(h)\nGROUP BY  UNIX_TIMESTAMP(CONVERT_TZ(h,'+00:00','+2:00')) DIV 86400 * 86400"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(CONVERT_TZ(h,'+00:00','+2:00')) DIV 86400 * 86400 AS \"time\",\n  sum(var2) AS \"export\"\nFROM VIEW1\nWHERE\n  $__timeFilter(h)\nGROUP BY  UNIX_TIMESTAMP(CONVERT_TZ(h,'+00:00','+2:00')) DIV 86400 * 86400"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(CONVERT_TZ(h,'+00:00','+2:00')) DIV 86400 * 86400 AS \"time\",\n  sum(var1) AS \"import\"\nFROM VIEW1\nWHERE\n  $__timeFilter(h)\nGROUP BY  UNIX_TIMESTAMP(CONVERT_TZ(h,'+00:00','+2:00')) DIV 86400 * 86400"
    }
   ]
  },
  {
   "title": "This Month",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Exported Energy",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kWh",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(CONVERT_TZ(h,'+00:00','+2:00')) DIV 86400 * 86400 AS \"time\",\n  sum(var2) AS \"production\"\nFROM VIEW2\nWHERE\n  $__timeFilter(h)\nGROUP BY  UNIX_TIMESTAMP(CONVERT_TZ(h,'+00:00','+2:00')) DIV 86400 * 86400",
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "exported_energy_monthly" }
     ]
    },
    {
     "alias": "Direct self-use",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kWh",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(CONVERT_TZ(h,'+00:00','+2:00')) DIV 86400 * 86400 AS \"time\",\n  sum(var1) AS \"consumption\"\nFROM VIEW2\nWHERE\n  $__timeFilter(h)\nGROUP BY  UNIX_TIMESTAMP(CONVERT_TZ(h,'+00:00','+2:00')) DIV 86400 * 86400",
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "selfuse_energy_monthly" }
     ]
    },
    {
     "alias": "Yield Energy",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kWh",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(CONVERT_TZ(h,'+00:00','+2:00')) DIV 86400 * 86400 AS \"time\",\n  sum(var2) AS \"export\"\nFROM VIEW1\nWHERE\n  $__timeFilter(h)\nGROUP BY  UNIX_TIMESTAMP(CONVERT_TZ(h,'+00:00','+2:00')) DIV 86400 * 86400",
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "yield_energy_monthly" }
     ]
    },
    {
     "alias": "Grid Consumption",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kWh",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(CONVERT_TZ(h,'+00:00','+2:00')) DIV 86400 * 86400 AS \"time\",\n  sum(var1) AS \"import\"\nFROM VIEW1\nWHERE\n  $__timeFilter(h)\nGROUP BY  UNIX_TIMESTAMP(CONVERT_TZ(h,'+00:00','+2:00')) DIV 86400 * 86400",
     "tags": [
      {
       "key": "entity_id",
       "operator": "=",
       "value": "grid_consumption_energy_monthly"
      }
     ]
    }
   ]
  },
  {
   "title": "Production",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "watth" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created,$__interval,NULL),\n  avg(var13*var14) AS \"production\"\nFROM QPIGS\nWHERE\n  $__timeFilter(created)\nGROUP BY $__timeGroup(created,$__interval,NULL)\n"
    }
   ]
  },
  {
   "title": "Production",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "watth" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(CONVERT_TZ(h,'+00:00','+2:00')) DIV 86400 * 86400 AS \"time\",\n  sum(var2) AS \"production\"\nFROM VIEW2\nWHERE\n  $__timeFilter(h)\nGROUP BY  UNIX_TIMESTAMP(CONVERT_TZ(h,'+00:00','+2:00')) DIV 86400 * 86400\n"
    }
   ]
  },
  {
   "title": "Consumption",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "watth" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created,$__interval,NULL),\n  avg(var6+60) AS \"consumption\"\nFROM QPIGS\nWHERE\n  $__timeFilter(created)\nGROUP BY $__timeGroup(created,$__interval,NULL)\n"
    }
   ]
  },
  {
   "title": "Consumption",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "watth" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(CONVERT_TZ(h,'+00:00','+2:00')) DIV 86400 * 86400 AS \"time\",\n  sum(var1) AS \"consumption\"\nFROM VIEW2\nWHERE\n  $__timeFilter(h)\nGROUP BY  UNIX_TIMESTAMP(CONVERT_TZ(h,'+00:00','+2:00')) DIV 86400 * 86400\n"
    }
   ]
  },
  {
   "title": "Grid balance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "watth" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created,$__interval,NULL),\n  if(avg(var8)>0,avg(var8),0) AS \"import\"\nFROM SDM230\nWHERE\n  $__timeFilter(created)\nGROUP BY $__timeGroup(created,$__interval,NULL)\n"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created,$__interval,NULL),\n  if(avg(var8)<0,avg(var8),0) AS \"export\"\nFROM SDM230\nWHERE\n  $__timeFilter(created)\nGROUP BY $__timeGroup(created,$__interval,NULL)"
    }
   ]
  },
  {
   "title": "Grid balance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "watth" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(CONVERT_TZ(h,'+00:00','+2:00')) DIV 86400 * 86400 AS \"time\",\n  sum(var1) AS \"import\"\nFROM VIEW1\nWHERE\n  $__timeFilter(h)\nGROUP BY  UNIX_TIMESTAMP(CONVERT_TZ(h,'+00:00','+2:00')) DIV 86400 * 86400\n"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(CONVERT_TZ(h,'+00:00','+2:00')) DIV 86400 * 86400 AS \"time\",\n  sum(var2) AS \"export\"\nFROM VIEW1\nWHERE\n  $__timeFilter(h)\nGROUP BY  UNIX_TIMESTAMP(CONVERT_TZ(h,'+00:00','+2:00')) DIV 86400 * 86400\n"
    }
   ]
  }
 ]
}