CREATE TABLE `axpert`.`QPIGS` (
  `created` timestamp NOT NULL DEFAULT current_timestamp(),
  `var1` float DEFAULT NULL,
  `var2` float DEFAULT NULL,
  `var3` float DEFAULT NULL,
  `var4` float DEFAULT NULL,
  `var5` float DEFAULT NULL,
  `var6` float DEFAULT NULL,
  `var7` float DEFAULT NULL,
  `var8` float DEFAULT NULL,
  `var9` float DEFAULT NULL,
  `var10` float DEFAULT NULL,
  `var11` float DEFAULT NULL,
  `var12` float DEFAULT NULL,
  `var13` float DEFAULT NULL,
  `var14` float DEFAULT NULL,
  `var15` float DEFAULT NULL,
  `var16` float DEFAULT NULL,
  PRIMARY KEY (`created`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
